# Generated by Django 5.1.6 on 2025-02-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groupsporttypes_group_active_group_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='competetive_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Open', 'Open'), ('Professional', 'Professional')], default='Open', max_length=200),
        ),
    ]
