# Generated by Django 5.1.6 on 2025-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_game_group_alter_group_organizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupscheduleevent',
            name='date_time',
        ),
        migrations.AddField(
            model_name='groupscheduleevent',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupscheduleevent',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='groupscheduleevent',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
