# Generated by Django 5.1.6 on 2025-02-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_event_alter_teamassignment_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='approved_by',
            field=models.ForeignKey(default='SYSTEM', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
