# Generated by Django 5.1.6 on 2025-02-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_groupmembership_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscheduleevent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
