# Generated by Django 5.1.6 on 2025-02-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_groupscheduleevent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscheduleevent',
            name='team_size',
            field=models.IntegerField(default=0),
        ),
    ]
