# Generated by Django 5.1.6 on 2025-02-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_groupscheduleevent_team_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscheduleevent',
            name='game_duration',
            field=models.IntegerField(default=0),
        ),
    ]
