# Generated by Django 5.1.6 on 2025-02-14 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_groupscheduleevent_game_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupscheduleevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupscheduleevent',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='groupscheduleevent',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
